import type { AgentType, AgentManifest } from '../types.js';
import {
  ALICE_MANIFEST,
  MAX_MANIFEST,
  FINN_MANIFEST,
  EVA_MANIFEST,
  ATLAS_MANIFEST,
  SAGE_MANIFEST,
  NOVA_MANIFEST,
  LYRA_MANIFEST,
  AURORA_MANIFEST,
  TITAN_MANIFEST,
  ORION_MANIFEST,
  MERCURY_MANIFEST,
  PHOENIX_MANIFEST,
  APOLLO_MANIFEST,
  GUARDIAN_MANIFEST,
} from '../manifests/index.js';

export interface AgentCapabilityDescriptor {
  manifest: AgentManifest;
  domain: string;
  tools: string[];
  delegatesTo: AgentType[];
  policies: string[];
  healthThreshold: number;
}

export const DIGITAL_WORKFORCE: Record<AgentType, AgentCapabilityDescriptor> = {
  alice: {
    manifest: ALICE_MANIFEST,
    domain: 'executive',
    tools: ['read_analytics', 'read_workflows', 'read_knowledge', 'query_alice'],
    delegatesTo: ['nova', 'sage', 'finn', 'guardian'],
    policies: ['require_executive_role', 'audit_all_queries'],
    healthThreshold: 0.95,
  },
  max: {
    manifest: MAX_MANIFEST,
    domain: 'operations',
    tools: ['trigger_workflows', 'write_tasks', 'read_workflows'],
    delegatesTo: ['atlas', 'lyra'],
    policies: ['audit_workflow_triggers'],
    healthThreshold: 0.9,
  },
  finn: {
    manifest: FINN_MANIFEST,
    domain: 'finance',
    tools: ['read_analytics', 'approve_decisions'],
    delegatesTo: ['guardian'],
    policies: ['require_finance_role', 'audit_approvals'],
    healthThreshold: 0.99,
  },
  eva: {
    manifest: EVA_MANIFEST,
    domain: 'hr',
    tools: ['read_workflows', 'read_knowledge', 'write_tasks', 'approve_decisions'],
    delegatesTo: ['atlas', 'lyra'],
    policies: ['require_hr_role', 'audit_people_actions'],
    healthThreshold: 0.95,
  },
  atlas: {
    manifest: ATLAS_MANIFEST,
    domain: 'knowledge',
    tools: ['read_knowledge', 'read_analytics'],
    delegatesTo: [],
    policies: ['audit_knowledge_access'],
    healthThreshold: 0.85,
  },
  sage: {
    manifest: SAGE_MANIFEST,
    domain: 'compliance',
    tools: ['read_workflows', 'read_analytics', 'read_knowledge', 'approve_decisions'],
    delegatesTo: ['guardian', 'atlas'],
    policies: ['require_compliance_role', 'audit_all_decisions', 'immutable_audit_trail'],
    healthThreshold: 0.99,
  },
  nova: {
    manifest: NOVA_MANIFEST,
    domain: 'analytics',
    tools: ['read_analytics', 'read_workflows', 'read_knowledge'],
    delegatesTo: ['atlas'],
    policies: ['audit_data_exports'],
    healthThreshold: 0.9,
  },
  lyra: {
    manifest: LYRA_MANIFEST,
    domain: 'communication',
    tools: ['read_workflows', 'write_tasks'],
    delegatesTo: [],
    policies: ['audit_broadcasts', 'require_broadcast_approval'],
    healthThreshold: 0.9,
  },
  aurora: {
    manifest: AURORA_MANIFEST,
    domain: 'workflow',
    tools: ['read_workflows', 'write_tasks', 'trigger_workflows', 'approve_decisions'],
    delegatesTo: ['max', 'lyra'],
    policies: ['audit_workflow_triggers', 'require_workflow_approval'],
    healthThreshold: 0.92,
  },
  titan: {
    manifest: TITAN_MANIFEST,
    domain: 'infrastructure',
    tools: ['read_analytics'],
    delegatesTo: ['guardian'],
    policies: ['require_admin_role', 'audit_infrastructure_actions', 'immutable_audit_trail'],
    healthThreshold: 0.99,
  },
  orion: {
    manifest: ORION_MANIFEST,
    domain: 'projects',
    tools: ['read_workflows', 'read_analytics', 'write_tasks'],
    delegatesTo: ['max', 'aurora'],
    policies: ['audit_project_actions'],
    healthThreshold: 0.9,
  },
  mercury: {
    manifest: MERCURY_MANIFEST,
    domain: 'integrations',
    tools: ['read_workflows', 'write_tasks', 'trigger_workflows'],
    delegatesTo: ['aurora'],
    policies: ['audit_integration_calls', 'require_integration_approval'],
    healthThreshold: 0.95,
  },
  phoenix: {
    manifest: PHOENIX_MANIFEST,
    domain: 'recovery',
    tools: ['read_workflows', 'read_analytics', 'approve_decisions'],
    delegatesTo: ['guardian', 'titan'],
    policies: ['require_admin_role', 'audit_recovery_actions', 'immutable_audit_trail'],
    healthThreshold: 0.99,
  },
  apollo: {
    manifest: APOLLO_MANIFEST,
    domain: 'learning',
    tools: ['read_knowledge', 'read_analytics', 'write_tasks'],
    delegatesTo: ['atlas'],
    policies: ['audit_training_actions'],
    healthThreshold: 0.88,
  },
  guardian: {
    manifest: GUARDIAN_MANIFEST,
    domain: 'security',
    tools: ['read_analytics', 'read_workflows', 'approve_decisions'],
    delegatesTo: [],
    policies: [
      'require_security_role',
      'audit_all_decisions',
      'immutable_audit_trail',
      'alert_on_threat',
    ],
    healthThreshold: 0.99,
  },
  // Legacy copilot agent types — not standalone workforce members but must satisfy the Record key constraint
  executive_copilot: {
    manifest: ALICE_MANIFEST,
    domain: 'executive',
    tools: ['read_analytics', 'read_workflows'],
    delegatesTo: ['alice'],
    policies: ['require_executive_role'],
    healthThreshold: 0.9,
  },
  operations_copilot: {
    manifest: MAX_MANIFEST,
    domain: 'operations',
    tools: ['read_workflows', 'write_tasks'],
    delegatesTo: ['max'],
    policies: [],
    healthThreshold: 0.9,
  },
  compliance_copilot: {
    manifest: SAGE_MANIFEST,
    domain: 'compliance',
    tools: ['read_workflows', 'read_analytics'],
    delegatesTo: ['sage'],
    policies: ['require_compliance_role'],
    healthThreshold: 0.95,
  },
  hr_copilot: {
    manifest: EVA_MANIFEST,
    domain: 'hr',
    tools: ['read_workflows', 'read_knowledge'],
    delegatesTo: ['eva'],
    policies: ['require_hr_role'],
    healthThreshold: 0.9,
  },
  finance_copilot: {
    manifest: FINN_MANIFEST,
    domain: 'finance',
    tools: ['read_analytics', 'approve_decisions'],
    delegatesTo: ['finn'],
    policies: ['require_finance_role'],
    healthThreshold: 0.95,
  },
  custom: {
    manifest: ALICE_MANIFEST,
    domain: 'custom',
    tools: [],
    delegatesTo: [],
    policies: [],
    healthThreshold: 0.8,
  },
};
