import type { Pool } from 'pg';

/**
 * Adds FORCE ROW LEVEL SECURITY to all tenant-scoped tables that had
 * ENABLE ROW LEVEL SECURITY but not FORCE. Without FORCE, the table owner
 * bypasses RLS policies, which undermines cross-tenant isolation guarantees.
 */
export async function up(pool: Pool): Promise<void> {
  const tables = [
    'abac_policies',
    'admin_notes',
    'agent_actions',
    'agent_insights',
    'agent_lifecycle_traces',
    'agent_permission_profiles',
    'api_keys',
    'approval_rules',
    'attendance_records',
    'autonomous_agents',
    'billing_accounts',
    'billing_profiles',
    'confidence_scores',
    'confidence_thresholds',
    'conversation_threads',
    'coo_actions',
    'coo_briefings',
    'credits',
    'dashboard_widgets',
    'delegations',
    'deployment_plans',
    'deployment_resources',
    'economy_accounts',
    'economy_transactions',
    'escalation_records',
    'execution_telemetry',
    'failure_records',
    'governance_approvals',
    'happy_path_simulations',
    'happy_path_templates',
    'healing_incidents',
    'healing_rules',
    'health_scores',
    'intelligence_contributions',
    'intelligence_snapshots',
    'invoice_items',
    'invoices',
    'knowledge_activities',
    'knowledge_categories',
    'knowledge_chunks',
    'knowledge_documents',
    'knowledge_tags',
    'knowledge_versions',
    'kpis',
    'loop_feedback',
    'loop_instances',
    'loop_learning_insights',
    'loop_optimization_recommendations',
    'loop_phase_insights',
    'loop_verifications',
    'metrics',
    'oauth_apps',
    'oauth_tokens',
    'org_configurations',
    'org_discovery_sessions',
    'org_dna',
    'org_graph_edges',
    'org_graph_nodes',
    'org_health_checkpoints',
    'org_health_scores',
    'org_hierarchy_nodes',
    'org_language_entries',
    'org_lifecycle_events',
    'org_memories',
    'org_memory_entries',
    'org_readiness_scores',
    'payments',
    'plans',
    'policies',
    'policy_enforcement_logs',
    'predictive_scores',
    'rate_limit_events',
    'recommendations',
    'reliability_reports',
    'report_templates',
    'reports',
    'retry_policies',
    'retry_records',
    'review_requests',
    'risk_alerts',
    'risk_indicators',
    'simulation_reports',
    'simulation_runs',
    'subscription_events',
    'subscriptions',
    'support_tickets',
    'threat_events',
    'trust_scores',
    'twin_nodes',
    'twin_relationships',
    'twin_snapshots',
    'usage_alerts',
    'usage_events',
    'usage_limits',
    'usage_records',
    'usage_summaries',
    'wa_templates',
    'webhook_deliveries',
    'webhooks',
    'workflow_generation_requests',
  ];

  for (const table of tables) {
    await pool.query(
      `DO $$ BEGIN
         IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = '${table}') THEN
           ALTER TABLE ${table} FORCE ROW LEVEL SECURITY;
         END IF;
       END $$`,
    );
  }
}

export async function down(pool: Pool): Promise<void> {
  const tables = [
    'abac_policies',
    'admin_notes',
    'agent_actions',
    'agent_insights',
    'agent_lifecycle_traces',
    'agent_permission_profiles',
    'api_keys',
    'approval_rules',
    'attendance_records',
    'autonomous_agents',
    'billing_accounts',
    'billing_profiles',
    'confidence_scores',
    'confidence_thresholds',
    'conversation_threads',
    'coo_actions',
    'coo_briefings',
    'credits',
    'dashboard_widgets',
    'delegations',
    'deployment_plans',
    'deployment_resources',
    'economy_accounts',
    'economy_transactions',
    'escalation_records',
    'execution_telemetry',
    'failure_records',
    'governance_approvals',
    'happy_path_simulations',
    'happy_path_templates',
    'healing_incidents',
    'healing_rules',
    'health_scores',
    'intelligence_contributions',
    'intelligence_snapshots',
    'invoice_items',
    'invoices',
    'knowledge_activities',
    'knowledge_categories',
    'knowledge_chunks',
    'knowledge_documents',
    'knowledge_tags',
    'knowledge_versions',
    'kpis',
    'loop_feedback',
    'loop_instances',
    'loop_learning_insights',
    'loop_optimization_recommendations',
    'loop_phase_insights',
    'loop_verifications',
    'metrics',
    'oauth_apps',
    'oauth_tokens',
    'org_configurations',
    'org_discovery_sessions',
    'org_dna',
    'org_graph_edges',
    'org_graph_nodes',
    'org_health_checkpoints',
    'org_health_scores',
    'org_hierarchy_nodes',
    'org_language_entries',
    'org_lifecycle_events',
    'org_memories',
    'org_memory_entries',
    'org_readiness_scores',
    'payments',
    'plans',
    'policies',
    'policy_enforcement_logs',
    'predictive_scores',
    'rate_limit_events',
    'recommendations',
    'reliability_reports',
    'report_templates',
    'reports',
    'retry_policies',
    'retry_records',
    'review_requests',
    'risk_alerts',
    'risk_indicators',
    'simulation_reports',
    'simulation_runs',
    'subscription_events',
    'subscriptions',
    'support_tickets',
    'threat_events',
    'trust_scores',
    'twin_nodes',
    'twin_relationships',
    'twin_snapshots',
    'usage_alerts',
    'usage_events',
    'usage_limits',
    'usage_records',
    'usage_summaries',
    'wa_templates',
    'webhook_deliveries',
    'webhooks',
    'workflow_generation_requests',
  ];

  for (const table of tables) {
    await pool.query(
      `DO $$ BEGIN
         IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = '${table}') THEN
           ALTER TABLE ${table} NO FORCE ROW LEVEL SECURITY;
         END IF;
       END $$`,
    );
  }
}
